ChatBotApp/Controllers/ChatRoomController.cs
using ChatBotApp.Models;
using ChatBotApp.Services;
using ChatBotApp.Utilities;
using ChatBotApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ChatBotApp.Controllers
{
  [Authorize]
  public class ChatRoomController : BaseController
  {
    private readonly ChatRoomService chatRoomService;
    private readonly ChatService chatService;
    private readonly IAuthorizationService authorizationService;
    public ChatRoomController(
      ChatRoomService chatRoomService, 
      IAuthorizationService authorizationService,
      ChatService chatService
    )
    {
      this.chatRoomService = chatRoomService;
      this.authorizationService = authorizationService;
      this.chatService = chatService;
    }

    public IActionResult Index()
    {
      try
      {
        var model = new ChatRoomIndexViewModel
        {
          OtherChats = chatRoomService.GetOthers(User.GetId()),
          UserChats = chatRoomService.GetAllByUserId(User.GetId())
        };
        return View(model);
      }
      catch (Exception ex)
      {
        return Error(ex.Message);
      }
    }

    public async Task<IActionResult> Show(long id, int limit = 50)
    {
      try
      {
        var authorizationResult =
          await authorizationService.AuthorizeAsync(User, id, "ChatRoomPolicy");
        if (!authorizationResult.Succeeded)
          return Forbid();

        var model = chatRoomService.GetById(id);
        if (model == null)
          return NotFound();

        model.Messages = chatService.GetAllByChatRoomId(id)
                                    .Take(50)
                                    .Reverse()
                                    .ToList();
        return View(model);
      }
      catch (Exception ex)
      {
        return Error(ex.Message);
      }
    }

    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Create(ChatRoomCreateModel model)
    {
      try
      {
        model.UserId = User.GetId();
        if (!ModelState.IsValid || chatRoomService.Create(model) == null)
          return View(model);
        
        TempData["Success"] = "Chat Room successfully created";

        return Redirect("/");
      }
      catch(Exception ex)
      {
        return Error(ex.Message);
      }
    }
  }
}

ChatBotApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - ChatBotApp</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container-fluid">
        @Html.ActionLink("ChatBotApp", "Index", "ChatRoom", null, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
          @(await Html.PartialAsync("_LoginPartial"))
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              @Html.ActionLink("ChatRooms", "Index", "ChatRoom", null, new { @class = "nav-link text-dark" })
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2022 - ChatBotApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  
  @if(TempData["Success"] != null)
  {
    <div class="toast bg-success text-white" style="position: absolute; top: 10px; right: 10px;">
      <div class="toast-body">
        @TempData["Success"]
      </div>
    </div>
  }else if(TempData["Error"] != null)
  {
    <div class="toast bg-danger text-white" style="position: absolute; top: 10px; right: 10px;">
      <div class="toast-body">
        @TempData["Error"]
      </div>
    </div>
  }
  <script>
    $('.toast').toast({ delay: 2000 }).toast('show');
  </script>
  @RenderSection("Scripts", required: false)
</body>
</html>