ChatBotApp/Entities/ChatRoom.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ChatBotApp.Entities
{
  [Index(nameof(Name), IsUnique = true)]
  public class ChatRoom
  {
    public long Id { get; set; }
    [Required]
    public string Name { get; set; }
  }
}

ChatBotApp/ViewModels/ChatRoomViewModel.cs
using System.Collections.Generic;

namespace ChatBotApp.ViewModels
{
  public class ChatRoomViewModel
  {
    public long Id { get; set; }
    public string Name { get; set; }
    public IEnumerable<ChatViewModel> Messages { get; set; }
  }
}

ChatBotApp/Controllers/ChatRoomController.cs
using ChatBotApp.Models;
using ChatBotApp.Services;
using ChatBotApp.Utilities;
using ChatBotApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ChatBotApp.Controllers
{
  [Authorize]
  public class ChatRoomController : BaseController
  {
    private readonly ChatRoomService chatRoomService;
    private readonly ChatService chatService;
    private readonly IAuthorizationService authorizationService;
    public ChatRoomController(
      ChatRoomService chatRoomService, 
      IAuthorizationService authorizationService,
      ChatService chatService
    )
    {
      this.chatRoomService = chatRoomService;
      this.authorizationService = authorizationService;
      this.chatService = chatService;
    }

    public IActionResult Index()
    {
      try
      {
        var model = new ChatRoomIndexViewModel
        {
          OtherChats = chatRoomService.GetOthers(User.GetId()),
          UserChats = chatRoomService.GetAllByUserId(User.GetId())
        };
        return View(model);
      }
      catch (Exception ex)
      {
        return Error(ex.Message);
      }
    }

    public async Task<IActionResult> Show(long id, int limit = 50)
    {
      try
      {
        var authorizationResult =
          await authorizationService.AuthorizeAsync(User, id, "ChatRoomPolicy");
        if (!authorizationResult.Succeeded)
          return Forbid();

        var model = chatRoomService.GetById(id);
        if (model == null)
          return NotFound();

        model.Messages = chatService.GetAllByChatRoomId(id)
                                    .Take(50)
                                    .Reverse()
                                    .ToList();
        return View(model);
      }
      catch (Exception ex)
      {
        return Error(ex.Message);
      }
    }

    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Create(ChatRoomCreateModel model)
    {
      try
      {
        model.UserId = User.GetId();
        if (!ModelState.IsValid || chatRoomService.Create(model) == null)
          return View(model);
        
        TempData["Success"] = "Chat Room successfully created";

        return Redirect("/");
      }
      catch(Exception ex)
      {
        return Error(ex.Message);
      }
    }
  }
}

ChatBotApp/Controllers/UserChatRoomController.cs
using ChatBotApp.Models;
using ChatBotApp.Services;
using ChatBotApp.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Claims;

namespace ChatBotApp.Controllers
{
  [Authorize]
  public class UserChatRoomController : BaseController
  {
    private readonly UserChatRoomService userChatRoomService;
    public UserChatRoomController(UserChatRoomService userChatRoomService)
    {
      this.userChatRoomService = userChatRoomService;
    }

    [HttpPost]
    public IActionResult Create(UserChatRoomCreateModel model)
    {
      try
      {
        if (!ModelState.IsValid)
          return View(model);

        model.UserId = User.GetId();
        userChatRoomService.Create(model);        
        TempData["Success"] = "User successfully joined chat room";

        return RedirectToAction("Show", "ChatRoom", new { id = model.ChatRoomId });
      }
      catch(Exception ex)
      {
        return Error(ex.Message);
      }
    }
  }
}

ChatBotApp/Views/ChatRoom/Create.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model ChatBotApp.Models.ChatRoomCreateModel

<div class="container">
  <h1 class="display-4">Create Chat Room</h1>

  @using (Html.BeginForm(FormMethod.Post))
  {
    <div class="form-group">
      @Html.LabelFor(m => m.Name, "Name")
      @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
      @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
    </div>
    <div class="form-group">
      <button class="btn btn-primary">Submit</button>
    </div>
  }
</div>

ChatBotApp/Views/ChatRoom/Index.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model ChatBotApp.ViewModels.ChatRoomIndexViewModel

@Html.ActionLink("New ChatRoom", "Create", "ChatRoom", null, new { @class = "btn btn-primary" })

<h2 class="mt-3">My Chat Rooms</h2>
<div class="d-flex flex-row mt-3">
  @foreach(var chatRoom in Model.UserChats)
  {
    @Html.ActionLink(chatRoom.Name, "Show", "ChatRoom", new { id = chatRoom.Id }, new { @class = "btn btn-success btn-sm mr-2" })      
  }
</div>
<h2 class="mt-3">Other Chat Rooms</h2>
<div class="d-flex flex-row mt-3">
  @foreach(var chatRoom in Model.OtherChats)
  {
    using(Html.BeginForm("Create", "UserChatRoom", FormMethod.Post))
    {
      @Html.Hidden("ChatRoomId", chatRoom.Id)
      <button class="btn btn-primary btn-sm mr-2">@chatRoom.Name</button>
    }
  }
</div>

ChatBotApp/Views/ChatRoom/Show.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model ChatBotApp.ViewModels.ChatRoomViewModel

@Html.Hidden("username", User.Identity.Name)

<h1>@Model.Name</h1>

<div class="chat-container">
  <div class="chat p-3" style="background-color: #eee;" data-chatroomid="@Model.Id">
    @foreach(var message in Model.Messages)
    {
      var isMine = message.Username == User.Identity.Name;
      <div class="d-flex @(isMine ? "justify-content-end" : "justify-content-start")" >
        <p class="p-2 rounded @(isMine ? "bg-success" : "bg-info") text-white text-wrap text-break" style="width: fit-content; max-width: 80%;">
          <b style="font-size: 11px;">[@message.CreatedAt]</b>
          @if (!isMine)
          {
            <b>@(message.Username): </b>
          }
          @message.Message
        </p>
      </div>
    }

  </div>
  
  <div class="d-flex">
    <div class="flex-fill">
      <textarea class="form-control rounded-0" data-messagechatroomid="@Model.Id" rows="1"></textarea>
    </div>
    <div>
      <button class="btn btn-primary btn-block sender px-5 rounded-0" data-buttonchatroomid="@Model.Id" type="button">Send</button>
    </div>      
  </div>  
</div>

@section Scripts{
  <script src="~/js/signalr/dist/browser/signalr.js"></script>
  <script src=~/js/chat.js></script> 
}